// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Zh3IGNe0mCIco3C5clYGf0xV8dW99Po',
    appId: '1:765889173380:web:17d9508ca183615d92afd1',
    messagingSenderId: '765889173380',
    projectId: 'smartfruit-6c05f',
    authDomain: 'smartfruit-6c05f.firebaseapp.com',
    storageBucket: 'smartfruit-6c05f.firebasestorage.app',
    measurementId: 'G-H9SYPL1RNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABMFj_aCwsm-BbsMTXFfCTjyIaDn5BcZQ',
    appId: '1:765889173380:android:58effedd00cd841092afd1',
    messagingSenderId: '765889173380',
    projectId: 'smartfruit-6c05f',
    storageBucket: 'smartfruit-6c05f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlFYwmbmeuM_iw3QdSInKbiqeHZVsi9o',
    appId: '1:765889173380:ios:d062a15830f8255592afd1',
    messagingSenderId: '765889173380',
    projectId: 'smartfruit-6c05f',
    storageBucket: 'smartfruit-6c05f.firebasestorage.app',
    iosBundleId: 'com.example.smartfruit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwlFYwmbmeuM_iw3QdSInKbiqeHZVsi9o',
    appId: '1:765889173380:ios:d062a15830f8255592afd1',
    messagingSenderId: '765889173380',
    projectId: 'smartfruit-6c05f',
    storageBucket: 'smartfruit-6c05f.firebasestorage.app',
    iosBundleId: 'com.example.smartfruit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Zh3IGNe0mCIco3C5clYGf0xV8dW99Po',
    appId: '1:765889173380:web:20bb00ebccb56a6a92afd1',
    messagingSenderId: '765889173380',
    projectId: 'smartfruit-6c05f',
    authDomain: 'smartfruit-6c05f.firebaseapp.com',
    storageBucket: 'smartfruit-6c05f.firebasestorage.app',
    measurementId: 'G-KJK3QXW7QC',
  );
}
